language: node_js
node_js:
  - "8"

git:
  depth: 1

before_install:
  - npm install -g vuepress

stages:
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script: vuepress build
    - stage: deploy
      script: echo "Deploying to GitHub Pages ..."
      deploy:
        local-dir: .vuepress/dist/
        fqdn: docs.whitestar.systems
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: gh-pages
