language: node_js
node_js:
  - "8"

cache: yarn

skip_cleanup: true

git:
  depth: 1

before_install:
  - yarn global add vuepress

jobs:
  include:
    - stage: build only
      if: branch IS NOT "master"
      script: vuepress build
    - stage: build & deploy
      if: branch IS "master"
      script: echo "Buidling Docs Site"
      script: vuepress build
      script: echo "Deploying to S3..."
      deploy:
        provider: s3
        access_key_id: $ACCESS_KEY
        secret_access_key: $ACCESS_SECRET
        bucket: "wss-docs"
        region: us-west-2
        local-dir: .vuepress/dist/
        acl: public_read
        detect_encoding: true
        default_text_charset: 'utf-8'
