language: node_js

git:
  depth: 1

before_install:
  - npm install -g vuepress

jobs:
  include:
    - stage: Build
      script: vuepress build
    - stage: Deploy - GitHub Pages
      script: echo "Deploying to GitHub Pages ..."
      deploy:
        local-dir: .vuepress/dist/
        fqdn: docs.whitestar.systems
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: gh-pages
