language: node_js
node_js:
  - "8"

cache: yarn

git:
  depth: 1

branches:
  only:
  - master

before_install:
  - yarn global add vuepress

jobs:
  include:
      script: echo "Buidling Docs Site"
      script: vuepress build -d docs
      script: echo "Deploying to S3..."
      deploy:
        provider: s3
        access_key_id: $ACCESS_KEY
        secret_access_key: $ACCESS_SECRET
        bucket: "wss-docs"
        region: us-west-2
        local-dir: docs
        acl: public_read
        skip_cleanup: true
        detect_encoding: true
        default_text_charset: 'utf-8'
