language: node_js
node_js:
  - "8"

git:
  depth: false

cache: yarn

before_install:
  - yarn global add vuepress

before_deploy:
  - echo "Deploying to GH Pages..."

jobs:
  include:
    - stage: build only
      if: branch != master
      script: echo "Buidling Docs Site" && vuepress build
    - stage: build & deploy
      if: branch = master
      script: echo "Buidling Docs Site" && vuepress build -d .build/docs
      deploy:
        provider: pages
        local-dir: .build/docs/
        fqdn: docs.whitestar.systems
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        target-branch: gh-pages
